import { NextResponse } from 'next/server';
import { getAnalyticsClient, getAnalyticsPropertyId } from '@/lib/analytics';
import { getPool, hasDb, ensureDb } from '@/lib/db';
import { requireRole } from '@/lib/auth';
import { emailLayout, escapeHtml, getNotificationEmails, sendMail } from '@/lib/mail';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Metrics = {
  users: number;
  newUsers: number;
  views: number;
  avgDuration: string;
  topPages: { name: string; views: number }[];
  topCountries: { name: string; users: number }[];
  cvDownloads: number;
  emailClicks: number;
  socialClicks: number;
  contactMessages: number;
};

function formatDuration(seconds: number): string {
  if (!seconds || isNaN(seconds)) return '0s';
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

/* Fila de la tabla de resumen. El estilo va inline: los clientes de correo
   descartan <style> y hojas externas. */
function metricRow(label: string, value: string | number, color: string, last = false): string {
  const border = last ? '' : 'border-bottom: 1px solid #e2e8f0;';
  return `
    <tr>
      <td style="padding: 12px 0; ${border}">
        <strong style="color: #334155; font-size: 16px;">${label}</strong>
      </td>
      <td style="padding: 12px 0; ${border} text-align: right;">
        <span style="font-size: 18px; font-weight: bold; color: ${color};">${value}</span>
      </td>
    </tr>
  `;
}

function eventRow(label: string, value: number, color: string, last = false): string {
  const border = last ? '' : 'border-bottom: 1px solid #e2e8f0;';
  return `
    <tr>
      <td style="padding: 10px 16px; ${border}">${label}</td>
      <td style="padding: 10px 16px; ${border} text-align: right; font-weight: bold; color: ${color};">${value}</td>
    </tr>
  `;
}

function buildReportHtml(m: Metrics): string {
  const list = (items: string[]) => `
    <ul style="margin: 0; padding-left: 20px; color: #475569; font-size: 14px;">
      ${items.map((i) => `<li style="margin-bottom: 4px;">${i}</li>`).join('')}
    </ul>
  `;

  const body = `
    <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px;">
      <table style="width: 100%; text-align: left; border-collapse: collapse;">
        ${metricRow('👤 Active users:', m.users, '#8b5cf6')}
        ${metricRow('✨ New users:', m.newUsers, '#10b981')}
        ${metricRow('👀 Total views:', m.views, '#8b5cf6')}
        ${metricRow('⏱️ Average time:', m.avgDuration, '#3b82f6', true)}
      </table>
    </div>

    ${m.topPages.length > 0 ? `
    <div style="margin-top: 24px;">
      <h3 style="color: #334155; font-size: 16px; margin-bottom: 12px;">📄 Top pages (most viewed)</h3>
      ${list(m.topPages.map((p) => `<strong>${escapeHtml(p.name)}</strong>: ${p.views} views`))}
    </div>
    ` : ''}

    ${m.topCountries.length > 0 ? `
    <div style="margin-top: 24px;">
      <h3 style="color: #334155; font-size: 16px; margin-bottom: 12px;">🌍 Top countries</h3>
      ${list(m.topCountries.map((c) => `<strong>${escapeHtml(c.name)}</strong>: ${c.users} users`))}
    </div>
    ` : ''}

    <div style="margin-top: 24px;">
      <h3 style="color: #334155; font-size: 16px; margin-bottom: 12px;">🎯 Key events</h3>
      <table style="width: 100%; text-align: left; border-collapse: collapse; font-size: 14px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px;">
        ${eventRow('📧 Email clicks', m.emailClicks, '#8b5cf6')}
        ${eventRow('📥 Messages received (form)', m.contactMessages, '#f59e0b')}
        ${eventRow('📄 CV downloads', m.cvDownloads, '#10b981')}
        ${eventRow('🔗 Social network clicks', m.socialClicks, '#3b82f6', true)}
      </table>
    </div>
  `;

  return emailLayout({
    title: 'Your weekly traffic report',
    subtitle: 'Summary of the last 7 days of your portfolio.',
    body,
    footer: 'Automatic report generated by your portfolio. Sign in to the admin panel for more detail.',
  });
}

function buildReportText(m: Metrics): string {
  return [
    'Your weekly traffic report',
    'Summary of the last 7 days of your portfolio.',
    '',
    `Active users: ${m.users}`,
    `New users: ${m.newUsers}`,
    `Total views: ${m.views}`,
    `Average time: ${m.avgDuration}`,
    '',
    ...(m.topPages.length ? ['Top pages:', ...m.topPages.map((p) => `  - ${p.name}: ${p.views} views`), ''] : []),
    ...(m.topCountries.length ? ['Top countries:', ...m.topCountries.map((c) => `  - ${c.name}: ${c.users} users`), ''] : []),
    'Key events:',
    `  Email clicks: ${m.emailClicks}`,
    `  Messages received (form): ${m.contactMessages}`,
    `  CV downloads: ${m.cvDownloads}`,
    `  Social network clicks: ${m.socialClicks}`,
    '',
    'Automatic report generated by your portfolio. Sign in to the admin panel for more detail.',
  ].join('\n');
}

export async function GET(req: Request) {
  // 1. Validar seguridad (CRON_SECRET o Sesión Admin)
  const cronSecret = process.env.CRON_SECRET;
  const url = new URL(req.url);
  const secretQuery = url.searchParams.get('secret');
  const preview = url.searchParams.get('preview') === 'true';
  const authHeader = req.headers.get('authorization');
  const bearerToken = authHeader?.startsWith('Bearer ') ? authHeader.split(' ')[1] : null;

  let isAuthorized = false;
  if (cronSecret && (secretQuery === cronSecret || bearerToken === cronSecret)) {
    isAuthorized = true;
  } else {
    try {
      const auth = await requireRole(req, ['owner', 'admin']);
      if (!('deny' in auth)) isAuthorized = true;
    } catch {
      // Ignorar
    }
  }

  if (!isAuthorized) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // 2. Verificar que GA4 esté configurado
  const analyticsClient = getAnalyticsClient();
  const propertyId = getAnalyticsPropertyId();
  if (!analyticsClient || !propertyId) {
    return NextResponse.json({ error: 'Google Analytics is not configured' }, { status: 500 });
  }

  // 3. Obtener datos de Google Analytics (últimos 7 días)
  const metricsData: Metrics = {
    users: 0,
    newUsers: 0,
    views: 0,
    avgDuration: '0s',
    topPages: [],
    topCountries: [],
    cvDownloads: 0,
    emailClicks: 0,
    socialClicks: 0,
    contactMessages: 0,
  };

  try {
    const [overviewRes, pagesRes, countriesRes, eventsRes] = await Promise.all([
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        metrics: [
          { name: 'activeUsers' },
          { name: 'newUsers' },
          { name: 'screenPageViews' },
          { name: 'averageSessionDuration' },
        ],
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'unifiedScreenName' }],
        metrics: [{ name: 'screenPageViews' }],
        limit: 10,
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'country' }],
        metrics: [{ name: 'activeUsers' }],
        limit: 3,
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'eventName' }],
        metrics: [{ name: 'eventCount' }]
      })
    ]);

    if (overviewRes[0].rows && overviewRes[0].rows.length > 0) {
      const row = overviewRes[0].rows[0];
      metricsData.users = parseInt(row.metricValues?.[0]?.value || '0', 10);
      metricsData.newUsers = parseInt(row.metricValues?.[1]?.value || '0', 10);
      metricsData.views = parseInt(row.metricValues?.[2]?.value || '0', 10);
      metricsData.avgDuration = formatDuration(parseFloat(row.metricValues?.[3]?.value || '0'));
    }

    if (pagesRes[0].rows) {
      const pageMap = new Map<string, number>();
      for (const r of pagesRes[0].rows) {
        const name = (r.dimensionValues?.[0]?.value || '(not set)').split(' - ')[0].split(' | ')[0].trim();
        const views = parseInt(r.metricValues?.[0]?.value || '0', 10);
        if (name && name !== '(not set)' && name !== '(other)') {
          pageMap.set(name, (pageMap.get(name) || 0) + views);
        }
      }
      metricsData.topPages = Array.from(pageMap.entries())
        .map(([name, views]) => ({ name, views }))
        .sort((a, b) => b.views - a.views)
        .slice(0, 5);
    }

    if (countriesRes[0].rows) {
      metricsData.topCountries = countriesRes[0].rows.map(r => ({
        name: r.dimensionValues?.[0]?.value || 'Unknown',
        users: parseInt(r.metricValues?.[0]?.value || '0', 10)
      }));
    }

    if (eventsRes[0].rows) {
      eventsRes[0].rows.forEach(r => {
        const eventName = r.dimensionValues?.[0]?.value || '';
        const count = parseInt(r.metricValues?.[0]?.value || '0', 10);
        if (eventName === 'cv_download') metricsData.cvDownloads += count;
        if (eventName === 'email_click') metricsData.emailClicks += count;
        if (eventName === 'social_click' || eventName.startsWith('social_click_')) {
          metricsData.socialClicks += count;
        }
      });
    }
  } catch (error) {
    console.error('[cron/report] Error fetching from GA4', error);
    return NextResponse.json({ error: 'Failed to fetch data from GA4' }, { status: 500 });
  }

  // 4. Completar con los mensajes recibidos y enviar
  await ensureDb();

  if (hasDb) {
    try {
      const pool = getPool()!;
      const { rows } = await pool.query(
        "SELECT COUNT(*)::int as count FROM contact_messages WHERE created_at >= NOW() - INTERVAL '7 days'"
      );
      metricsData.contactMessages = rows[0]?.count || 0;
    } catch (e) {
      console.error('[cron/report] DB Error:', e);
    }
  }

  const htmlContent = buildReportHtml(metricsData);

  /* El preview se resuelve antes de tocar el mailer: solo renderiza el HTML y
     no necesita ni credenciales ni destinatarios. */
  if (preview) {
    return new NextResponse(htmlContent, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' }
    });
  }

  const result = await sendMail({
    to: await getNotificationEmails(),
    subject: '[Portfolio] Weekly Traffic Report',
    html: htmlContent,
    text: buildReportText(metricsData),
    fromName: 'Portfolio Analytics',
  });

  if (!result.sent) {
    console.error('[cron/report] report not sent:', result.reason);
    /* Falta de configuración → el reporte se generó igual, no es una caída.
       Un rechazo del proveedor sí es un fallo: 500 para que el monitor del
       cron lo marque en vez de contarlo como ejecución exitosa. */
    const status = result.code === 'send_failed' ? 500 : 200;
    return NextResponse.json({
      success: status === 200,
      message: `Report generated but not sent: ${result.reason}`,
      data: metricsData,
    }, { status });
  }

  return NextResponse.json({ success: true, data: metricsData });
}
