import { NextResponse } from 'next/server';
import { getAnalyticsClient, getAnalyticsPropertyId } from '@/lib/analytics';
import { getPool, hasDb, ensureDb } from '@/lib/db';
import { requireRole } from '@/lib/auth';
import { emailLayout, escapeHtml, getNotificationEmails, sendMail } from '@/lib/mail';
// imports removed to avoid Next.js static analysis error

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Metrics = {
  users: number;
  newUsers: number;
  views: number;
  topPages: { name: string; views: number }[];
  topCountries: { name: string; users: number }[];
  cvDownloads: number;
  emailClicks: number;
  socialClicks: { network: string; count: number }[];
  contactMessages: number;
  historicalMapSvg?: string;
};

/* Fila de la tabla de resumen. El estilo va inline: los clientes de correo
   descartan <style> y hojas externas. */
function metricRow(label: string, value: string | number, last = false): string {
  const border = last ? '' : 'border-bottom: 1px solid #e2e8f0;';
  return `
    <tr>
      <td style="padding: 12px 0; ${border}">
        <strong style="color: #475569; font-size: 15px; font-weight: 500;">${label}</strong>
      </td>
      <td style="padding: 12px 0; ${border} text-align: right;">
        <span style="font-size: 16px; font-weight: 600; color: #0f172a;">${value}</span>
      </td>
    </tr>
  `;
}

function eventRow(label: string, value: number, last = false): string {
  const border = last ? '' : 'border-bottom: 1px solid #e2e8f0;';
  return `
    <tr>
      <td style="padding: 10px 16px; ${border} color: #475569; font-size: 14px;">${label}</td>
      <td style="padding: 10px 16px; ${border} text-align: right; font-weight: 600; color: #0f172a;">${value}</td>
    </tr>
  `;
}

function buildReportHtml(m: Metrics): string {
  const list = (items: string[]) => `
    <ul style="margin: 0; padding-left: 20px; color: #475569; font-size: 14px;">
      ${items.map((i) => `<li style="margin-bottom: 8px;">${i}</li>`).join('')}
    </ul>
  `;

  const socialRows = m.socialClicks.length > 0 
    ? m.socialClicks.map((s, i) => eventRow(`- ${s.network}`, s.count, i === m.socialClicks.length - 1)).join('')
    : eventRow('- None', 0, true);

  const body = `
    <div style="background: #ffffff; border: 1px solid #e2e8f0; border-radius: 6px; padding: 24px;">
      <h2 style="font-size: 18px; font-weight: 600; color: #0f172a; margin: 0 0 16px 0;">Audience Overview</h2>
      <table style="width: 100%; text-align: left; border-collapse: collapse;">
        ${metricRow('Active users', m.users)}
        ${metricRow('New users', m.newUsers)}
        ${metricRow('Total views', m.views, true)}
      </table>
    </div>

    ${m.topPages.length > 0 ? `
    <div style="margin-top: 32px;">
      <h3 style="color: #0f172a; font-size: 15px; font-weight: 600; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Top pages (most viewed)</h3>
      ${list(m.topPages.map((p) => `<span style="color: #0f172a; font-weight: 500;">${escapeHtml(p.name)}</span>: ${p.views} views`))}
    </div>
    ` : ''}

    ${m.topCountries.length > 0 ? `
    <div style="margin-top: 32px;">
      <h3 style="color: #0f172a; font-size: 15px; font-weight: 600; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Top countries (this week)</h3>
      ${list(m.topCountries.map((c) => `<span style="color: #0f172a; font-weight: 500;">${escapeHtml(c.name)}</span>: ${c.users} users`))}
    </div>
    ` : ''}

    ${m.historicalMapSvg ? `
    <div style="margin-top: 32px;">
      <h3 style="color: #0f172a; font-size: 15px; font-weight: 600; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Historical Global Reach</h3>
      <div style="background: #f8fafc; border-radius: 6px; padding: 16px; overflow: hidden; text-align: center;">
        ${m.historicalMapSvg}
      </div>
    </div>
    ` : ''}

    <div style="margin-top: 32px;">
      <h3 style="color: #0f172a; font-size: 15px; font-weight: 600; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Key events</h3>
      <table style="width: 100%; text-align: left; border-collapse: collapse; font-size: 14px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 6px;">
        ${eventRow('Email clicks', m.emailClicks)}
        ${eventRow('Messages received (form)', m.contactMessages)}
        ${eventRow('CV downloads', m.cvDownloads)}
        <tr>
          <td colspan="2" style="padding: 10px 16px; color: #475569; font-size: 14px; background: #f8fafc; font-weight: 500;">Social network clicks</td>
        </tr>
        ${socialRows}
      </table>
    </div>
  `;

  return emailLayout({
    title: 'Weekly Traffic Report',
    subtitle: 'Summary of the last 7 days of your portfolio.',
    body,
    footer: 'Automatic report generated by your portfolio. Sign in to the admin panel for more detail.',
  });
}

function buildReportText(m: Metrics): string {
  return [
    'Weekly Traffic Report',
    'Summary of the last 7 days of your portfolio.',
    '',
    `Active users: ${m.users}`,
    `New users: ${m.newUsers}`,
    `Total views: ${m.views}`,
    '',
    ...(m.topPages.length ? ['Top pages:', ...m.topPages.map((p) => `  - ${p.name}: ${p.views} views`), ''] : []),
    ...(m.topCountries.length ? ['Top countries (this week):', ...m.topCountries.map((c) => `  - ${c.name}: ${c.users} users`), ''] : []),
    'Key events:',
    `  Email clicks: ${m.emailClicks}`,
    `  Messages received (form): ${m.contactMessages}`,
    `  CV downloads: ${m.cvDownloads}`,
    `  Social network clicks:`,
    ...(m.socialClicks.length ? m.socialClicks.map((s) => `    - ${s.network}: ${s.count}`) : ['    - None']),
    '',
    'Automatic report generated by your portfolio. Sign in to the admin panel for more detail.',
  ].join('\n');
}

export async function GET(req: Request) {
  // 1. Validar seguridad (CRON_SECRET o Sesión Admin)
  const cronSecret = process.env.CRON_SECRET;
  const url = new URL(req.url);
  const secretQuery = url.searchParams.get('secret');
  const preview = url.searchParams.get('preview') === 'true';
  const authHeader = req.headers.get('authorization');
  const bearerToken = authHeader?.startsWith('Bearer ') ? authHeader.split(' ')[1] : null;

  let isAuthorized = false;
  if (cronSecret && (secretQuery === cronSecret || bearerToken === cronSecret)) {
    isAuthorized = true;
  } else {
    try {
      const auth = await requireRole(req, ['owner', 'admin']);
      if (!('deny' in auth)) isAuthorized = true;
    } catch {
      // Ignorar
    }
  }

  if (!isAuthorized) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // 2. Verificar que GA4 esté configurado
  const analyticsClient = getAnalyticsClient();
  const propertyId = getAnalyticsPropertyId();
  if (!analyticsClient || !propertyId) {
    return NextResponse.json({ error: 'Google Analytics is not configured' }, { status: 500 });
  }

  // 3. Obtener datos de Google Analytics
  const metricsData: Metrics = {
    users: 0,
    newUsers: 0,
    views: 0,
    topPages: [],
    topCountries: [],
    cvDownloads: 0,
    emailClicks: 0,
    socialClicks: [],
    contactMessages: 0,
  };

  try {
    const [overviewRes, pagesRes, countriesRes, eventsRes, historicalRes] = await Promise.all([
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        metrics: [
          { name: 'activeUsers' },
          { name: 'newUsers' },
          { name: 'screenPageViews' }
        ],
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'unifiedScreenName' }],
        metrics: [{ name: 'screenPageViews' }],
        limit: 10,
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'country' }],
        metrics: [{ name: 'activeUsers' }],
        limit: 3,
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '7daysAgo', endDate: 'yesterday' }],
        dimensions: [{ name: 'eventName' }],
        metrics: [{ name: 'eventCount' }]
      }),
      analyticsClient.runReport({
        property: `properties/${propertyId}`,
        dateRanges: [{ startDate: '2020-01-01', endDate: 'yesterday' }],
        dimensions: [{ name: 'countryId' }],
        metrics: [{ name: 'activeUsers' }]
      })
    ]);

    if (overviewRes[0].rows && overviewRes[0].rows.length > 0) {
      const row = overviewRes[0].rows[0];
      metricsData.users = parseInt(row.metricValues?.[0]?.value || '0', 10);
      metricsData.newUsers = parseInt(row.metricValues?.[1]?.value || '0', 10);
      metricsData.views = parseInt(row.metricValues?.[2]?.value || '0', 10);
    }

    if (pagesRes[0].rows) {
      const pageMap = new Map<string, number>();
      for (const r of pagesRes[0].rows) {
        const name = (r.dimensionValues?.[0]?.value || '(not set)').split(' - ')[0].split(' | ')[0].trim();
        const views = parseInt(r.metricValues?.[0]?.value || '0', 10);
        if (name && name !== '(not set)' && name !== '(other)') {
          pageMap.set(name, (pageMap.get(name) || 0) + views);
        }
      }
      metricsData.topPages = Array.from(pageMap.entries())
        .map(([name, views]) => ({ name, views }))
        .sort((a, b) => b.views - a.views)
        .slice(0, 5);
    }

    if (countriesRes[0].rows) {
      metricsData.topCountries = countriesRes[0].rows.map(r => ({
        name: r.dimensionValues?.[0]?.value || 'Unknown',
        users: parseInt(r.metricValues?.[0]?.value || '0', 10)
      }));
    }

    if (eventsRes[0].rows) {
      const socialMap = new Map<string, number>();
      eventsRes[0].rows.forEach(r => {
        const eventName = r.dimensionValues?.[0]?.value || '';
        const count = parseInt(r.metricValues?.[0]?.value || '0', 10);
        if (eventName === 'cv_download') metricsData.cvDownloads += count;
        if (eventName === 'email_click') metricsData.emailClicks += count;
        if (eventName === 'social_click') {
          // Legacy fallback
          socialMap.set('Unknown', (socialMap.get('Unknown') || 0) + count);
        } else if (eventName.startsWith('social_click_')) {
          const network = eventName.replace('social_click_', '');
          const formattedNetwork = network.charAt(0).toUpperCase() + network.slice(1);
          socialMap.set(formattedNetwork, (socialMap.get(formattedNetwork) || 0) + count);
        }
      });
      metricsData.socialClicks = Array.from(socialMap.entries())
        .map(([network, count]) => ({ network, count }))
        .sort((a, b) => b.count - a.count);
    }

    if (historicalRes[0].rows) {
      const mapData = historicalRes[0].rows
        .filter(r => r.dimensionValues?.[0]?.value && r.dimensionValues[0].value !== '(not set)')
        .map(r => ({
          country: (r.dimensionValues?.[0]?.value || '').toLowerCase(),
          value: parseInt(r.metricValues?.[0]?.value || '0', 10)
        }));
        
      if (mapData.length > 0) {
        try {
          // Use dynamic require to prevent Next.js static analysis from failing the build
          const React = require('react');
          const { renderToStaticMarkup } = require('react-dom/server');
          const WorldMap = require('react-svg-worldmap').default || require('react-svg-worldmap');
          
          metricsData.historicalMapSvg = renderToStaticMarkup(
            React.createElement(WorldMap, {
              color: '#475569',
              backgroundColor: 'transparent',
              borderColor: '#e2e8f0',
              valueSuffix: 'users',
              size: 'responsive', // Note: emails don't execute JS for responsive maps, but width=100% helps.
              data: mapData
            } as any)
          );
          // Patch the rendered SVG string. react-svg-worldmap renders it wrapped in div/figure which have width: 100%. 
          // We can just keep it as is, standard html should render fine.
        } catch (err) {
          console.error('[cron/report] Error rendering WorldMap SVG:', err);
        }
      }
    }

  } catch (error) {
    console.error('[cron/report] Error fetching from GA4', error);
    return NextResponse.json({ error: 'Failed to fetch data from GA4' }, { status: 500 });
  }

  // 4. Completar con los mensajes recibidos y enviar
  await ensureDb();

  if (hasDb) {
    try {
      const pool = getPool()!;
      const { rows } = await pool.query(
        "SELECT COUNT(*)::int as count FROM contact_messages WHERE created_at >= NOW() - INTERVAL '7 days'"
      );
      metricsData.contactMessages = rows[0]?.count || 0;
    } catch (e) {
      console.error('[cron/report] DB Error:', e);
    }
  }

  const htmlContent = buildReportHtml(metricsData);

  /* El preview se resuelve antes de tocar el mailer: solo renderiza el HTML y
     no necesita ni credenciales ni destinatarios. */
  if (preview) {
    return new NextResponse(htmlContent, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' }
    });
  }

  const result = await sendMail({
    to: await getNotificationEmails(),
    subject: '[Portfolio] Weekly Traffic Report',
    html: htmlContent,
    text: buildReportText(metricsData),
    fromName: 'Portfolio Analytics',
  });

  if (!result.sent) {
    console.error('[cron/report] report not sent:', result.reason);
    /* Falta de configuración → el reporte se generó igual, no es una caída.
       Un rechazo del proveedor sí es un fallo: 500 para que el monitor del
       cron lo marque en vez de contarlo como ejecución exitosa. */
    const status = result.code === 'send_failed' ? 500 : 200;
    return NextResponse.json({
      success: status === 200,
      message: `Report generated but not sent: ${result.reason}`,
      data: metricsData,
    }, { status });
  }

  return NextResponse.json({ success: true, data: metricsData });
}
